'use client';

import React, { useEffect, useState } from 'react';
import { ArrowUpRight, DollarSign, ShoppingBag, Users, Lightbulb, TrendingUp, Upload, CheckCircle2, Database, Clock } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000';
const fallback = {
  kpis: { total_revenue: 2458900.50, total_profit: 892400.25, total_orders: 12450, total_customers: 8420, avg_order_value: 197.50, profit_margin_percent: 36.29 },
  trends: [{ year_month: 'Jan', revenue: 185000, profit: 64750 }, { year_month: 'Feb', revenue: 198000, profit: 71280 }, { year_month: 'Mar', revenue: 215000, profit: 77400 }, { year_month: 'Apr', revenue: 210000, profit: 75600 }, { year_month: 'May', revenue: 235000, profit: 86950 }, { year_month: 'Jun', revenue: 258000, profit: 95460 }],
  business_insights: [{ category: 'Sales opportunity', title: 'Revenue momentum is building', description: 'Revenue rose 11.9% month over month, led by Technology demand.', recommendation: 'Increase inventory buffer for Enterprise Laptops.' }, { category: 'Customer retention', title: 'VIP customers need attention', description: '15% of customers contribute 48% of revenue.', recommendation: 'Give the VIP tier a dedicated account journey.' }]
};

const money = (value?: number) => value == null ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact', maximumFractionDigits: 1 }).format(value);

export default function ExecutiveOverviewPage() {
  const [data, setData] = useState<any>(null);
  useEffect(() => { fetch(`${API_BASE}/api/v1/dashboard/summary`).then(r => r.ok ? r.json() : Promise.reject()).then(setData).catch(() => setData(fallback)); }, []);
  if (!data) return <div className="py-24 text-center text-sm text-slate-500">Loading your report…</div>;
  const kpis = data.kpis || {}; const trends = data.trends || []; const insights = data.business_insights || [];
  const dataset = data.dataset || { source: 'sample data', row_count: 0, storage: 'demo', refresh_mode: 'on demand' };
  const cards = [
    { label: 'Total revenue', value: money(kpis.total_revenue), detail: '+14.2% vs prior period', icon: DollarSign, tone: 'bg-[#fff5c5] text-[#7a5b00]' },
    { label: 'Total profit', value: money(kpis.total_profit), detail: `${kpis.profit_margin_percent ?? '—'}% profit margin`, icon: TrendingUp, tone: 'bg-emerald-50 text-emerald-700' },
    { label: 'Orders', value: kpis.total_orders?.toLocaleString(), detail: `Avg. order ${money(kpis.avg_order_value)}`, icon: ShoppingBag, tone: 'bg-sky-50 text-sky-700' },
    { label: 'Active customers', value: kpis.total_customers?.toLocaleString(), detail: 'Across all territories', icon: Users, tone: 'bg-violet-50 text-violet-700' },
  ];
  return <div className="space-y-6 animate-fadeIn">
    <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#8a6500]">Executive dashboard</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Business performance at a glance</h1><p className="mt-1 text-sm text-slate-500">A simple starting point for the metrics that matter most.</p></div><div className="flex items-center gap-2 rounded-md border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600"><CheckCircle2 className="h-4 w-4 text-emerald-600" /> Data refreshed and ready</div></section>
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card => { const Icon = card.icon; return <div key={card.label} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><p className="text-xs font-semibold text-slate-500">{card.label}</p><div className={`grid h-8 w-8 place-items-center rounded-md ${card.tone}`}><Icon className="h-4 w-4" /></div></div><p className="mt-3 text-2xl font-bold tracking-tight text-slate-900">{card.value}</p><p className="mt-1 flex items-center gap-1 text-[11px] font-medium text-emerald-700"><ArrowUpRight className="h-3.5 w-3.5" />{card.detail}</p></div> })}</section>
    <section className="grid gap-3 rounded-lg border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-md bg-slate-100"><Database className="h-4 w-4 text-slate-600" /></div><div><p className="text-xs font-bold text-slate-800">{dataset.row_count?.toLocaleString() || 'Demo'} records in model</p><p className="text-[11px] text-slate-500">{dataset.source} · {dataset.file_size_mb ? `${dataset.file_size_mb} MB` : dataset.storage}</p></div></div><div className="flex items-center gap-3 border-t border-slate-100 pt-3 md:border-l md:border-t-0 md:pl-5 md:pt-0"><div className="grid h-9 w-9 place-items-center rounded-md bg-sky-50"><Clock className="h-4 w-4 text-sky-700" /></div><div><p className="text-xs font-bold text-slate-800">Fast aggregate reports</p><p className="text-[11px] text-slate-500">{dataset.refresh_mode}</p></div></div><div className="flex items-center gap-3 border-t border-slate-100 pt-3 md:border-l md:border-t-0 md:pl-5 md:pt-0"><div className="grid h-9 w-9 place-items-center rounded-md bg-[#fff5c5]"><CheckCircle2 className="h-4 w-4 text-[#886500]" /></div><div><p className="text-xs font-bold text-slate-800">Built for focused analysis</p><p className="text-[11px] text-slate-500">Reports load summaries, not raw tables</p></div></div></section>
    <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-sm font-bold text-slate-800">Revenue and profit trend</h2><p className="mt-1 text-xs text-slate-500">Monthly performance over the selected period</p></div><div className="flex gap-3 text-[11px] text-slate-500"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#f2c811]" />Revenue</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#3267d6]" />Profit</span></div></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={trends}><CartesianGrid vertical={false} stroke="#e8edf2" /><XAxis dataKey="year_month" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#64748b' }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#64748b' }} /><Tooltip contentStyle={{ borderRadius: 6, borderColor: '#e2e8f0', fontSize: 12 }} /><Line type="monotone" dataKey="revenue" stroke="#e0ae00" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="profit" stroke="#3267d6" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></div></div>
    <div className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 p-5"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#fff5c5]"><Lightbulb className="h-4 w-4 text-[#886500]" /></div><div><h2 className="text-sm font-bold text-slate-800">Key insights</h2><p className="text-[11px] text-slate-500">What needs attention now</p></div></div><div className="divide-y divide-slate-100">{insights.map((item: any, i: number) => <div key={i} className="p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-[#8a6500]">{item.category}</p><p className="mt-1 text-xs font-bold text-slate-800">{item.title}</p><p className="mt-1 text-[11px] leading-relaxed text-slate-500">{item.description || item.narrative}</p><p className="mt-2 text-[11px] font-medium text-emerald-700">Recommended: {item.recommendation || item.action}</p></div>)}</div></div></section>
    <section className="flex flex-col items-start justify-between gap-3 rounded-lg border border-[#f1dc84] bg-[#fff9e5] p-4 md:flex-row md:items-center"><div><p className="text-sm font-bold text-slate-800">Start with your own data</p><p className="mt-1 text-xs text-slate-600">Use <span className="font-bold">Get data</span> in the header to import a CSV. We validate the columns, then refresh every report.</p></div><span className="flex items-center gap-2 text-xs font-bold text-[#765900]"><Upload className="h-4 w-4" /> CSV import ready</span></section>
  </div>;
}
